name = "TypedDelegation"
uuid = "bc724e2e-2423-57c2-8f10-788c81380fc8"
repo = "https://github.com/JeffreySarnoff/TypedDelegation.jl.git"
author = "Jeffrey Sarnoff"
license = "MIT"
version = "v0.5.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1"
